[project]
name = "inventory-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest-asyncio>=1.2.0",
    "temporalio>=1.18.1",
    "trio>=0.31.0",
]
